"""init tables

Revision ID: 6e05bd8d4591
Revises: 
Create Date: 2025-09-26 15:58:20.330809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e05bd8d4591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengukuran',
    sa.Column('id_pengukuran', sa.Integer(), nullable=False),
    sa.Column('id_anak', sa.Integer(), nullable=False),
    sa.Column('id_perawat', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('lingkar_kepala', sa.Float(), nullable=True),
    sa.Column('lingkar_lengan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_pengukuran')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengukuran')
    # ### end Alembic commands ###
